### ISSUE TITLE
Payment

### ISSUE THREAD

**Issue by Cordelro86** [stripe-samples/developer-office-hours#118]
# Bug report

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Server environment [e.g. Go, Java, Node, PHP, Python, Ruby, TypeScript]

**Comment by cjavilla-stripe** [comment]
Not enough information.

**Comment by Cordelro** [comment]
Receive payment 3400$
